name: trie
description: A comprehensive Trie implementation in Dart, optimized for autocomplete.
version: 1.0.1
homepage: https://github.com/dark-mode/Trie
authors:  [Christopher Gong <christophergong@berkeley.edu>, Ankush Vangari <ankush@vangari.com>]

environment:
  sdk: '>=2.2.2 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.14.6
